# -*- coding: utf-8 -*-
TEST_YAHOO_STOCK_UNIVERSE_16 = ("XOM",
                                "GS",
                                "T",
                                "AAPL",
                                "MSFT",
                                "PG",
                                "K",
                                "ADI",
                                "GE",
                                "AIG",
                                "KO",
                                "NKE",
                                "BAC",
                                "MMM",
                                "AXP",
                                "AMZN",
                                )
